owner: kubernetes
repo: kops
assets:
  - source: .build/dist/darwin/amd64/kops
    githubName: kops-darwin-amd64
  - source: .build/dist/darwin/amd64/kops.sha256
    githubName: kops-darwin-amd64.sha256
  - source: .build/dist/linux/amd64/kops
    githubName: kops-linux-amd64
  - source: .build/dist/linux/amd64/kops.sha256
    githubName: kops-linux-amd64.sha256
  - source: .build/dist/linux/arm64/kops
    githubName: kops-linux-arm64
  - source: .build/dist/linux/arm64/kops.sha256
    githubName: kops-linux-arm64.sha256
  - source: .build/dist/windows/amd64/kops.exe
    githubName: kops-windows-amd64
  - source: .build/dist/windows/amd64/kops.exe.sha256
    githubName: kops-windows-amd64.sha256
  - source: .build/dist/images/protokube.tar.gz
    githubName: images-protokube.tar.gz
  - source: .build/dist/images/protokube.tar.gz.sha256
    githubName: images-protokube.tar.gz.sha256
  - source: .build/dist/linux/amd64/nodeup
    githubName: linux-amd64-nodeup
  - source: .build/dist/linux/amd64/nodeup.sha256
    githubName: linux-amd64-nodeup.sha256
  - source: .build/dist/linux/arm64/nodeup
    githubName: linux-arm64-nodeup
  - source: .build/dist/linux/arm64/nodeup.sha256
    githubName: linux-arm64-nodeup.sha256
