executors:
  machine-executor:
    machine:
      resource_class: medium
      image: ubuntu-2004:202010-01
    environment:
      GOPATH: $CIRCLE_WORKING_DIRECTORY/gopath

jobs:
  build:
    exeuctor: machine-executor
    steps:
      - checkout:
          name: $GOPATH/src/k8s.io/kops

      - run: find .

      - run: make -d echo-version

      # Pre-upload build steps.
      - run: make bazel-crossbuild-nodeup


