version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium

    # For some reason it is difficult to set a global override for GOPATH.
    # For the record, we choose a GOPATH of `$CIRCLE_WORKING_DIRECTORY/gopath`.
    # We manually reference this in a bunch of places.

    steps:
      - checkout:
          name: ./gopath/src/k8s.io/kops

      - run:
          command: env
          environment:
            GOPATH: "$CIRCLE_WORKING_DIRECTORY/gopath"

      - run:
          command: make -d echo-version
          environment:
            GOPATH: "$CIRCLE_WORKING_DIRECTORY/gopath"

      # Pre-upload build steps.
      - run:
          command: make bazel-crossbuild-nodeup
          environment:
            GOPATH: "$CIRCLE_WORKING_DIRECTORY/gopath"

