version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium

    # It seems like CircleCI doesn't like it when I override GOPATH.  It just
    # re-overrides my override with its own broken values.  Great.  We set the
    # value inside each and every command so that it actually sticks.

    steps:
      - checkout:
          name: ./gopath/src/k8s.io/kops

      - run:
          command: |
            export GOPATH="$CIRCLE_WORKING_DIRECTORY/gopath"
            env

      - run:
          command: make -d echo-version
          environment:
            GOPATH: "$CIRCLE_WORKING_DIRECTORY/gopath"

      # Pre-upload build steps.
      - run:
          command: make bazel-crossbuild-nodeup
          environment:
            GOPATH: "$CIRCLE_WORKING_DIRECTORY/gopath"

