jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
      environment:
        GOPATH: $CIRCLE_WORKING_DIRECTORY/gopath
    resource_class: medium
    steps:
      - checkout:
        name: $CIRCLE_WORKING_DIRECTORY/gopath/src/k8s.io/kops

      - run: find .

      - run: make -d echo-version

      # Pre-upload build steps.
      - run: make bazel-crossbuild-nodeup


