jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium
    steps:
      - checkout
      - run: find .

      - run: make echo-version

      # Pre-upload build steps.
      - run: bazel-crossbuild-nodeup


